happy linter, happy life

diff --git a/bin/project_root b/bin/project_root
--- a/bin/project_root
+++ b/bin/project_root
@@ -2,12 +2,12 @@
 
 # Find the root of a project if it is located on Source. Also check for some common prefixes
 
-DIR=$(find -L ~/Projects -name "$1" -maxdepth 2 -type d)
+DIR=$(find -L ~/Projects -maxdepth 2 -type d -iname "$1")
 
 if [ "$DIR" != "" ]; then
     echo $DIR
     exit 0
 fi
 
-echo "$1 Doesn't exist"
+echo "'$1' not found"  1>&2
 exit 1
